project_id = "75hard"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = []

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
max_frequency = "1m0s"
otp_length = 8
